name: "TruffleHog Security Scan"

on:
  push:
    branches: ["**"]

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@v3.4.1
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
      - name: Create
        id: create
        uses: ./
        with:
          project: SEC
          issuetype: Vulnerability
          summary: |
            Github Action | TruffleHog | ${{ github.repository }}
          description: |
            TruffleHog result: \n${{join(steps.trufflehog.outputs.*, '\n')}}
      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
        
