name: "TruffleHog Security Scan"

on:
  push:
    branches: ["**"]

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@v3.4.1
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
        continue-on-error: true
      # - name: Create
      #   id: create
      #   if: contains(${{steps.trufflehog.outputs.*}}, 'Found')
      #   uses: atlassian/gajira-create@v2.0.1
      #   with:
      #     project: SEC
      #     issuetype: Vulnerability
      #     summary: |
      #       [Github Action | TruffleHog] | ${{ github.repository }}
      #     description: |
      #       TruffleHog result: join(${{steps.trufflehog.outputs.*}}, '\n')
      - name: Log created issue
        run: echo "Issue ${{ steps.trufflehog.outputs.* }} was created"
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: tonylab
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_MESSAGE: '${{steps.trufflehog.outputs.*}}'
          SLACK_TITLE: TruffleHog Findings
          SLACK_USERNAME: GAbot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
