name: "TruffleHog Security Scan"

on:
  push:
    branches: ["**"]

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.trufflehog.outputs.test }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout private tool code
        uses: actions/checkout@v2
        with:
          repository: ph20Eoow/private_action
          path: actions/my-action
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      # - name: TruffleHog OSS
      #   id: trufflehog
      #   uses: trufflesecurity/trufflehog@v3.4.1
      #   with:
      #     path: ./
      #     base: ${{ github.event.repository.default_branch }}
      #     head: HEAD
      #   run: echo "::set-output name=test::test"
      #   continue-on-error: true
      - name: Echo WORKSPACE
        run: echo "$github.GITHUB_WORKSPACE"
      - name: Hello world action step
        id: hello
        uses: ./actions/my-action
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      # - name: Create
      #   id: create
      #   if: contains(${{steps.trufflehog.outputs.*}}, 'Found')
      #   uses: atlassian/gajira-create@v2.0.1
      #   with:
      #     project: SEC
      #     issuetype: Vulnerability
      #     summary: |
      #       [Github Action | TruffleHog] | ${{ github.repository }}
      #     description: |
      #       TruffleHog result: join(${{steps.trufflehog.outputs.*}}, '\n')
      - name: Log created issue
        run: echo "Issue ${{ steps.trufflehog.outputs.* }} was created"
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\n${{ steps.trufflehog.outputs.* }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
