name: "TruffleHog Security Scan"

on:
  push:
    branches: ["**"]

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.trufflehog.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout private tool code
        uses: actions/checkout@v2
        with:
          repository: ph20Eoow/private_action
          path: ./.github/
      
      - name: TruffleHog Scan from Private Action 
        id: trufflehog
        uses: ./.github/actions/trufflehog
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
  PrintResult:
    runs-on: ubuntu-latest
    needs: TruffleHog
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: access the result
        run: echo "Issue ${{ needs.TruffleHog.outputs.result }} was created"
      - name: Echo WORKSPACE
        run: "ls -la ${{ github.workspace }}"
      - name: Create
        id: create
        if: contains('${{needs.TruffleHog.outputs.result}}', '[')
        run: echo "Issue ${{ needs.TruffleHog.outputs.result }} was created"
      #   uses: atlassian/gajira-create@v2.0.1
      #   with:
      #     project: SEC
      #     issuetype: Vulnerability
      #     summary: |
      #       [Github Action | TruffleHog] | ${{ github.repository }}
      #     description: |
      #       TruffleHog result: join(${{steps.trufflehog.outputs.*}}, '\n')
      